# Site settings
title: Oliver Tinsman
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oliver Tinsman
user_description: 
user_title: Sales Engineer
email: tinsman@pm.me
# twitter_username: lorem_ipsum
linkedin_username: olivertinsman
github_username:  happytechnology
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

